language: c
compiler: gcc

os: linux
dist: bionic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-10

script:
  - export CC=gcc-10
  - export CXX=g++-10
  - cmake .
  - make

deploy:
  provider: releases
  api_key:
    secure: "E6/amP3N+EW69WyCA3LFC0DN7YTe6+wK1Bir4ry/JNrysQ6ds6/5oQT0aYnsPsFykIgh9EBYjwc1QJiUS/+3zG6N97XPafw3gtZSBqzxYjd7uKovS9Dp15RqjGPUdpih4rUw/7ecaS+eT+xilPt3aEtKdmQpW6Lvvd7Rt6FlXhfVE4zfZCJm9KrYksthx2Gml/CN+i4eTbXhAfCZFT3QKBOIdlxwgxbCPLR01KVJs0fbhQmp0cofqUhT5lWLDm8oMKZvIn8K5p5j3DDHGh0VGo5hZhKFxWJ2lxSCiokGRFnk+aGBgBLLnHwq1L2jlF+JX3qQ/8Bwg/SQmTpq8Pcb381/Wcue93v5zFGo1lKSbBw7tiYIEwA8/jngxm9GagoIOV1bAiabHb8WEH9Q/59mYKWiMxJYohKDfY3czK+J7LU13wfnDVEuZmKqrJ415GJR+cLjlHOkGgJ9pSU62j46rupT4fdMUDAYE2qpEgIbsnULQ6N5qhxdQq2G13JmI3tIJe64T+VMdXsVJ9oFWf5Sn7oOx/+744vHYu/KIqjEjfBNy974pxDuIjmoFtM4pGT0DYMWZPicMb+bx5B6llyiyoOFQjNbM7CI7Hx/qe/jwHWz185GVim5xXyYi9pPsutssTtfchIYpLcQdzbtqLmsKxaqHTqI6pzsG7vXXz/mf9g="
  file: "DEternal_patchManifest"
  skip_cleanup: true
  on:
    tags: true